const fs = require('node:fs');
const path = require('node:path');
const {
  MARKERS,
  CLAUDE_RULE_DEFINITIONS,
  CLAUDE_MD_SNIPPET,
  CLAUDE_SKILL_CONTENT,
  CLAUDE_HOOK_SCRIPT,
} = require('../constants');

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

/**
 * Build a .claude/rules/ file from a content section.
 * Each rule definition maps to a CONTENT_SECTIONS entry by section name.
 */
function buildRuleFile(definition, sections) {
  const section = sections.find((s) => s.section === definition.contentSection);
  const content = section
    ? section.files.map((f) => f.content.trim()).join('\n\n---\n\n')
    : `<!-- No content found for section: ${definition.contentSection} -->`;

  return [
    '---',
    `description: "${definition.description}"`,
    `globs: "${definition.globs}"`,
    '---',
    '',
    `# Tenets: ${definition.contentSection} Rules`,
    '',
    '> Auto-generated by tenets. Run `npx tenets update` to update.',
    '',
    content,
    '',
  ].join('\n');
}

/**
 * Write all Claude Code integration files:
 * 1. .claude/rules/tenets-*.md  — glob-based auto-loading rules
 * 2. CLAUDE.md snippet          — top-level principles (appended/replaced)
 * 3. .claude/skills/tenets-review-architecture/SKILL.md — on-demand review command
 * 4. .claude/hooks/check-architecture.js — continuous monitoring hook
 */
function writeClaudeIntegration(projectRoot, content) {
  const { sections } = content;
  const writtenFiles = [];

  // --- Layer 1: Rule files ---
  const rulesDir = path.join(projectRoot, '.claude', 'rules');
  ensureDir(rulesDir);

  for (const definition of CLAUDE_RULE_DEFINITIONS) {
    const ruleContent = buildRuleFile(definition, sections);
    const rulePath = path.join(rulesDir, definition.fileName);
    fs.writeFileSync(rulePath, ruleContent, 'utf-8');
    writtenFiles.push(`.claude/rules/${definition.fileName}`);
  }

  // Clean up stale rule files from pre-0.4.0 installs
  const staleRuleFiles = ['tenets-synergy.md', 'tenets-ports-adapters.md', 'tenets-structure.md'];
  for (const stale of staleRuleFiles) {
    const stalePath = path.join(rulesDir, stale);
    if (fs.existsSync(stalePath)) {
      fs.unlinkSync(stalePath);
    }
  }

  // --- Layer 2: CLAUDE.md snippet ---
  const claudeMdPath = path.join(projectRoot, 'CLAUDE.md');
  writeClaudeMdSnippet(claudeMdPath);
  writtenFiles.push('CLAUDE.md');

  // --- Layer 3: Skill file ---
  const skillDir = path.join(projectRoot, '.claude', 'skills', 'tenets-review-architecture');
  ensureDir(skillDir);
  const skillPath = path.join(skillDir, 'SKILL.md');
  fs.writeFileSync(skillPath, CLAUDE_SKILL_CONTENT, 'utf-8');
  writtenFiles.push('.claude/skills/tenets-review-architecture/SKILL.md');

  // Clean up old skill directory from pre-0.4.2 installs
  const oldSkillDir = path.join(projectRoot, '.claude', 'skills', 'review-architecture');
  if (fs.existsSync(oldSkillDir)) {
    fs.rmSync(oldSkillDir, { recursive: true });
  }

  // --- Layer 4: Hook script ---
  const hookDir = path.join(projectRoot, '.claude', 'hooks');
  ensureDir(hookDir);
  const hookPath = path.join(hookDir, 'check-architecture.js');
  fs.writeFileSync(hookPath, CLAUDE_HOOK_SCRIPT, 'utf-8');
  fs.chmodSync(hookPath, 0o755);
  writtenFiles.push('.claude/hooks/check-architecture.js');

  return { writtenFiles };
}

/**
 * Append or replace the tenets block in CLAUDE.md.
 */
function writeClaudeMdSnippet(claudeMdPath) {
  if (fs.existsSync(claudeMdPath)) {
    const existing = fs.readFileSync(claudeMdPath, 'utf-8');
    const startIdx = existing.indexOf(MARKERS.start);
    const endIdx = existing.indexOf(MARKERS.end);

    if (startIdx !== -1 && endIdx !== -1) {
      const before = existing.substring(0, startIdx);
      const after = existing.substring(endIdx + MARKERS.end.length);
      fs.writeFileSync(claudeMdPath, before + CLAUDE_MD_SNIPPET + after, 'utf-8');
    } else {
      const separator = existing.endsWith('\n') ? '\n' : '\n\n';
      fs.writeFileSync(claudeMdPath, existing + separator + CLAUDE_MD_SNIPPET + '\n', 'utf-8');
    }
  } else {
    const content = ['# CLAUDE.md', '', CLAUDE_MD_SNIPPET, ''].join('\n');
    fs.writeFileSync(claudeMdPath, content, 'utf-8');
  }
}

/**
 * Write the hook configuration into .claude/settings.json.
 */
function writeHookSettings(projectRoot) {
  const settingsPath = path.join(projectRoot, '.claude', 'settings.json');

  let settings = {};
  if (fs.existsSync(settingsPath)) {
    try {
      settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    } catch {
      settings = {};
    }
  }

  if (!settings.hooks) {
    settings.hooks = {};
  }

  if (!settings.hooks.PostToolUse) {
    settings.hooks.PostToolUse = [];
  }

  const tenetsHookExists = settings.hooks.PostToolUse.some((entry) =>
    entry.hooks?.some((h) => h.command?.includes('check-architecture'))
  );

  if (!tenetsHookExists) {
    settings.hooks.PostToolUse.push({
      matcher: 'Edit|Write',
      hooks: [
        {
          type: 'command',
          command: 'node .claude/hooks/check-architecture.js',
        },
      ],
    });
  }

  ensureDir(path.dirname(settingsPath));
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');

  return '.claude/settings.json';
}

module.exports = { writeClaudeIntegration, writeHookSettings };
