const fs = require('node:fs');
const path = require('node:path');
const {
  MARKERS,
  CLAUDE_RULE_DEFINITIONS,
  CLAUDE_MD_SNIPPET,
  CLAUDE_SKILL_CONTENT,
  CLAUDE_HOOK_SCRIPT,
} = require('../constants');

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

/**
 * Extract sections from the assembled rules content by matching markdown headings.
 * Each CLAUDE_RULE_DEFINITION has contentSections — an array of heading strings
 * that correspond to `## Heading` in the rules file.
 */
function extractSectionContent(rulesContent, sectionHeadings) {
  const lines = rulesContent.split('\n');
  const extractedParts = [];

  for (const heading of sectionHeadings) {
    let capturing = false;
    let capturedLines = [];
    let headingLevel = null;
    let inCodeFence = false;

    for (const line of lines) {
      // Track code fences so we don't mistake code comments for headings
      if (line.startsWith('```')) {
        inCodeFence = !inCodeFence;
        if (capturing) {
          capturedLines.push(line);
        }
        continue;
      }

      if (!inCodeFence) {
        const headingMatch = line.match(/^(#{1,3})\s+(.+)/);

        if (headingMatch) {
          const level = headingMatch[1].length;
          const text = headingMatch[2].trim();

          if (text === heading) {
            capturing = true;
            headingLevel = level;
            capturedLines.push(line);
            continue;
          }

          // Stop capturing when we hit a heading at the same or higher level
          if (capturing && level <= headingLevel) {
            capturing = false;
          }
        }
      }

      if (capturing) {
        capturedLines.push(line);
      }
    }

    if (capturedLines.length > 0) {
      extractedParts.push(capturedLines.join('\n').trim());
    }
  }

  return extractedParts.join('\n\n---\n\n');
}

/**
 * Build a .claude/rules/ file with frontmatter.
 */
function buildRuleFile(definition, rulesContent) {
  const sectionContent = extractSectionContent(rulesContent, definition.contentSections);

  return [
    '---',
    `description: "${definition.description}"`,
    `globs: "${definition.globs}"`,
    '---',
    '',
    `# Tenets: ${definition.description.split(':')[0]}`,
    '',
    '> Auto-generated by tenets. Run `npx tenets update` to update.',
    '',
    sectionContent || `<!-- No matching sections found for: ${definition.contentSections.join(', ')} -->`,
    '',
  ].join('\n');
}

/**
 * Write all Claude Code integration files:
 * 1. .claude/rules/tenets-*.md  — glob-based auto-loading rules
 * 2. CLAUDE.md snippet          — top-level principles (appended/replaced)
 * 3. .claude/skills/review-architecture/SKILL.md — on-demand review command
 * 4. .claude/hooks/check-architecture.js — continuous monitoring hook
 *
 * Returns an object describing what was written.
 */
function writeClaudeIntegration(projectRoot, rulesContent) {
  const writtenFiles = [];

  // --- Layer 1: Rule files ---
  const rulesDir = path.join(projectRoot, '.claude', 'rules');
  ensureDir(rulesDir);

  for (const definition of CLAUDE_RULE_DEFINITIONS) {
    const ruleContent = buildRuleFile(definition, rulesContent);
    const rulePath = path.join(rulesDir, definition.fileName);
    fs.writeFileSync(rulePath, ruleContent, 'utf-8');
    writtenFiles.push(`.claude/rules/${definition.fileName}`);
  }

  // --- Layer 2: CLAUDE.md snippet ---
  const claudeMdPath = path.join(projectRoot, 'CLAUDE.md');
  writeClaudeMdSnippet(claudeMdPath);
  writtenFiles.push('CLAUDE.md');

  // --- Layer 3: Skill file ---
  const skillDir = path.join(projectRoot, '.claude', 'skills', 'review-architecture');
  ensureDir(skillDir);
  const skillPath = path.join(skillDir, 'SKILL.md');
  fs.writeFileSync(skillPath, CLAUDE_SKILL_CONTENT, 'utf-8');
  writtenFiles.push('.claude/skills/review-architecture/SKILL.md');

  // --- Layer 4: Hook script ---
  const hookDir = path.join(projectRoot, '.claude', 'hooks');
  ensureDir(hookDir);
  const hookPath = path.join(hookDir, 'check-architecture.js');
  fs.writeFileSync(hookPath, CLAUDE_HOOK_SCRIPT, 'utf-8');
  fs.chmodSync(hookPath, 0o755);
  writtenFiles.push('.claude/hooks/check-architecture.js');

  return { writtenFiles };
}

/**
 * Append or replace the tenets block in CLAUDE.md.
 * If markers exist, replaces the content between them.
 * If CLAUDE.md exists but has no markers, appends.
 * If CLAUDE.md doesn't exist, creates it.
 */
function writeClaudeMdSnippet(claudeMdPath) {
  if (fs.existsSync(claudeMdPath)) {
    const existing = fs.readFileSync(claudeMdPath, 'utf-8');
    const startIdx = existing.indexOf(MARKERS.start);
    const endIdx = existing.indexOf(MARKERS.end);

    if (startIdx !== -1 && endIdx !== -1) {
      // Replace existing markers
      const before = existing.substring(0, startIdx);
      const after = existing.substring(endIdx + MARKERS.end.length);
      fs.writeFileSync(claudeMdPath, before + CLAUDE_MD_SNIPPET + after, 'utf-8');
    } else {
      // Append to existing file
      const separator = existing.endsWith('\n') ? '\n' : '\n\n';
      fs.writeFileSync(claudeMdPath, existing + separator + CLAUDE_MD_SNIPPET + '\n', 'utf-8');
    }
  } else {
    // Create new CLAUDE.md
    const content = [
      '# CLAUDE.md',
      '',
      CLAUDE_MD_SNIPPET,
      '',
    ].join('\n');
    fs.writeFileSync(claudeMdPath, content, 'utf-8');
  }
}

/**
 * Write the hook configuration into .claude/settings.json.
 * Merges with existing settings if present.
 */
function writeHookSettings(projectRoot) {
  const settingsPath = path.join(projectRoot, '.claude', 'settings.json');

  let settings = {};
  if (fs.existsSync(settingsPath)) {
    try {
      settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    } catch {
      // If settings.json is malformed, start fresh
      settings = {};
    }
  }

  if (!settings.hooks) {
    settings.hooks = {};
  }

  if (!settings.hooks.PostToolUse) {
    settings.hooks.PostToolUse = [];
  }

  // Check if tenets hook already configured
  const tenetsHookExists = settings.hooks.PostToolUse.some((entry) =>
    entry.hooks?.some((h) => h.command?.includes('check-architecture'))
  );

  if (!tenetsHookExists) {
    settings.hooks.PostToolUse.push({
      matcher: 'Edit|Write',
      hooks: [
        {
          type: 'command',
          command: 'node .claude/hooks/check-architecture.js',
        },
      ],
    });
  }

  ensureDir(path.dirname(settingsPath));
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');

  return '.claude/settings.json';
}

module.exports = { writeClaudeIntegration, writeHookSettings, extractSectionContent };
