const fs = require('node:fs');
const path = require('node:path');
const {
  GENERATED_MARKER,
  MARKERS,
  CLAUDE_RULE_DEFINITIONS,
  CLAUDE_MD_SNIPPET,
  CODE_REVIEW_AGENT_NAME,
  CLAUDE_CODE_REVIEW_AGENT_TEMPLATE,
  CODE_REVIEW_AGENT_HOOK_PROMPT_TEMPLATE,
  CLAUDE_HOOK_SCRIPT,
} = require('../constants');
const {
  writeReviewCommand,
  reviewCommandPath,
  reviewCommandExists,
} = require('./review-command-writer');
const {
  assertCanWriteOwnedFiles,
  isTenetsOwnedFile,
  upsertMarkedContent,
  writeOwnedFile,
} = require('./file-writer');

const CLI_ROOT = path.join(__dirname, '..', '..');

function readCliFile(relativePath) {
  return fs.readFileSync(path.join(CLI_ROOT, relativePath), 'utf-8');
}

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

/**
 * Build a .claude/rules/ file from a content section.
 * Each rule definition maps to a CONTENT_SECTIONS entry by section name.
 */
function buildRuleFile(definition, sections) {
  const section = sections.find((s) => s.section === definition.contentSection);
  const content = section
    ? section.files.map((f) => f.content.trim()).join('\n\n---\n\n')
    : `<!-- No content found for section: ${definition.contentSection} -->`;

  return [
    '---',
    `description: "${definition.description}"`,
    `globs: "${definition.globs}"`,
    '---',
    '',
    GENERATED_MARKER,
    '',
    `# Tenets: ${definition.contentSection} Rules`,
    '',
    '> Auto-generated by tenets. Run `npx tenets update` to update.',
    '',
    content,
    '',
  ].join('\n');
}

/**
 * Write all Claude Code integration files:
 * 1. .claude/rules/tenets-*.md  — glob-based auto-loading rules
 * 2. CLAUDE.md snippet          — top-level principles (appended/replaced)
 * 3. .claude/skills/tenets-review-architecture/SKILL.md — on-demand review command
 * 4. .claude/hooks/check-architecture.js — continuous monitoring hook
 * 5. .claude/agents/code-review-agent.md — optional Claude Code subagent
 */
function claudeOwnedPaths(projectRoot, options = {}) {
  const paths = [
    ...CLAUDE_RULE_DEFINITIONS.map((definition) =>
      path.join(projectRoot, '.claude', 'rules', definition.fileName)
    ),
    reviewCommandPath(projectRoot, 'claude'),
    path.join(projectRoot, '.claude', 'hooks', 'check-architecture.js'),
  ];

  if (options.installCodeReviewAgent) {
    paths.push(
      path.join(
        projectRoot,
        '.claude',
        'agents',
        `${CODE_REVIEW_AGENT_NAME}.md`
      )
    );
  }
  return paths;
}

function removeOwnedFile(filePath) {
  if (isTenetsOwnedFile(filePath)) {
    fs.unlinkSync(filePath);
    return true;
  }
  return false;
}

function removeDirectoryIfEmpty(directoryPath) {
  if (
    fs.existsSync(directoryPath) &&
    fs.readdirSync(directoryPath).length === 0
  ) {
    fs.rmdirSync(directoryPath);
  }
}

function writeClaudeIntegration(projectRoot, content, options = {}) {
  const { sections } = content;
  const {
    installCodeReviewAgent = false,
    overwriteConflicts = false,
  } = options;
  const writtenFiles = [];
  assertCanWriteOwnedFiles(
    claudeOwnedPaths(projectRoot, { installCodeReviewAgent }),
    { overwriteConflicts }
  );

  // --- Layer 1: Rule files ---
  const rulesDir = path.join(projectRoot, '.claude', 'rules');
  ensureDir(rulesDir);

  for (const definition of CLAUDE_RULE_DEFINITIONS) {
    const ruleContent = buildRuleFile(definition, sections);
    const rulePath = path.join(rulesDir, definition.fileName);
    writeOwnedFile(rulePath, ruleContent, { overwriteConflicts });
    writtenFiles.push(`.claude/rules/${definition.fileName}`);
  }

  // Clean up stale rule files from pre-0.4.0 installs
  const staleRuleFiles = ['tenets-synergy.md', 'tenets-ports-adapters.md', 'tenets-structure.md'];
  for (const stale of staleRuleFiles) {
    const stalePath = path.join(rulesDir, stale);
    removeOwnedFile(stalePath);
  }

  // --- Layer 2: CLAUDE.md snippet ---
  const claudeMdPath = path.join(projectRoot, 'CLAUDE.md');
  const claudeMdAction = writeClaudeMdSnippet(claudeMdPath);
  writtenFiles.push('CLAUDE.md');

  // --- Layer 3: Skill file ---
  const skillFile = writeReviewCommand(projectRoot, 'claude', {
    overwriteConflicts,
    content,
  });
  writtenFiles.push(skillFile);
  const skillDir = path.join(projectRoot, '.claude', 'skills', 'tenets-review-architecture');

  // Clean up old skill files from pre-0.6.0 installs (renamed from SKILL.md to TENETS-SKILL.md)
  const oldSkillPath = path.join(skillDir, 'SKILL.md');
  removeOwnedFile(oldSkillPath);

  // Clean up old skill directory from pre-0.4.2 installs
  const oldSkillDir = path.join(projectRoot, '.claude', 'skills', 'review-architecture');
  removeOwnedFile(path.join(oldSkillDir, 'SKILL.md'));
  removeOwnedFile(path.join(oldSkillDir, 'TENETS-SKILL.md'));
  removeDirectoryIfEmpty(oldSkillDir);

  if (installCodeReviewAgent) {
    const agentDir = path.join(projectRoot, '.claude', 'agents');
    ensureDir(agentDir);
    const agentPath = path.join(agentDir, `${CODE_REVIEW_AGENT_NAME}.md`);
    writeOwnedFile(
      agentPath,
      readCliFile(CLAUDE_CODE_REVIEW_AGENT_TEMPLATE)
        .replace('{{ACTIVE_PROFILE}}', content.profile)
        .replace(
          '{{ACTIVE_RULE_IDS}}',
          content.activeRuleIds.map((id) => `- \`${id}\``).join('\n')
        ),
      { overwriteConflicts }
    );
    writtenFiles.push(`.claude/agents/${CODE_REVIEW_AGENT_NAME}.md`);
  }

  // --- Layer 4: Hook script ---
  const hookDir = path.join(projectRoot, '.claude', 'hooks');
  ensureDir(hookDir);
  const hookPath = path.join(hookDir, 'check-architecture.js');
  writeOwnedFile(hookPath, CLAUDE_HOOK_SCRIPT, { overwriteConflicts });
  fs.chmodSync(hookPath, 0o755);
  writtenFiles.push('.claude/hooks/check-architecture.js');

  return { writtenFiles, claudeMdAction };
}

/**
 * Append or replace the tenets block in CLAUDE.md.
 * Returns 'created' | 'appended' | 'replaced' to let callers log what happened.
 */
function writeClaudeMdSnippet(claudeMdPath) {
  return upsertMarkedContent(
    claudeMdPath,
    CLAUDE_MD_SNIPPET,
    '# CLAUDE.md'
  );
}

function readSettings(settingsPath) {
  if (!fs.existsSync(settingsPath)) {
    return {};
  }

  try {
    const settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    if (!settings || Array.isArray(settings) || typeof settings !== 'object') {
      throw new Error('expected a JSON object');
    }
    return settings;
  } catch (error) {
    throw new Error(
      `Refusing to overwrite malformed shared settings file: ${settingsPath}. ` +
      `Fix the JSON and retry. (${error.message})`
    );
  }
}

function getPostToolUseHooks(settings, settingsPath) {
  if (settings.hooks === undefined) {
    settings.hooks = {};
  } else if (
    !settings.hooks ||
    Array.isArray(settings.hooks) ||
    typeof settings.hooks !== 'object'
  ) {
    throw new Error(
      `Refusing to modify shared settings with a non-object hooks value: ${settingsPath}`
    );
  }

  if (settings.hooks.PostToolUse === undefined) {
    settings.hooks.PostToolUse = [];
  } else if (!Array.isArray(settings.hooks.PostToolUse)) {
    throw new Error(
      `Refusing to modify shared settings with a non-array hooks.PostToolUse value: ${settingsPath}`
    );
  }

  return settings.hooks.PostToolUse;
}

/**
 * Write the hook configuration into .claude/settings.json.
 */
function writeHookSettings(projectRoot) {
  const settingsPath = path.join(projectRoot, '.claude', 'settings.json');

  const settings = readSettings(settingsPath);
  const postToolUseHooks = getPostToolUseHooks(settings, settingsPath);
  const tenetsHookExists = postToolUseHooks.some((entry) =>
    entry?.hooks?.some((hook) =>
      hook?.command?.includes('check-architecture')
    )
  );

  if (!tenetsHookExists) {
    postToolUseHooks.push({
      matcher: 'Edit|Write',
      hooks: [
        {
          type: 'command',
          command: 'node .claude/hooks/check-architecture.js',
        },
      ],
    });
  }

  ensureDir(path.dirname(settingsPath));
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');

  return '.claude/settings.json';
}

function writeCodeReviewAgentHookSettings(projectRoot) {
  const settingsPath = path.join(projectRoot, '.claude', 'settings.json');

  const settings = readSettings(settingsPath);
  const postToolUseHooks = getPostToolUseHooks(settings, settingsPath);
  const tenetsCodeReviewHookExists = postToolUseHooks.some((entry) =>
    entry?.hooks?.some((hook) =>
      hook?.type === 'agent' &&
      hook?.prompt?.includes('Tenets code review agent')
    )
  );

  if (!tenetsCodeReviewHookExists) {
    postToolUseHooks.push({
      matcher: 'Edit|MultiEdit|Write',
      hooks: [
        {
          type: 'agent',
          prompt: readCliFile(CODE_REVIEW_AGENT_HOOK_PROMPT_TEMPLATE).trim(),
          timeout: 120,
          continueOnBlock: true,
        },
      ],
    });
  }

  ensureDir(path.dirname(settingsPath));
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');

  return '.claude/settings.json';
}

function claudeIntegrationComplete(projectRoot) {
  const claudeMdPath = path.join(projectRoot, 'CLAUDE.md');
  const hasSnippet =
    fs.existsSync(claudeMdPath) &&
    fs.readFileSync(claudeMdPath, 'utf-8').includes(MARKERS.start);
  const hasRules = CLAUDE_RULE_DEFINITIONS.every((definition) =>
    isTenetsOwnedFile(
      path.join(projectRoot, '.claude', 'rules', definition.fileName)
    )
  );
  const hasHookScript = isTenetsOwnedFile(
    path.join(projectRoot, '.claude', 'hooks', 'check-architecture.js')
  );

  return (
    hasSnippet &&
    hasRules &&
    hasHookScript &&
    reviewCommandExists(projectRoot, 'claude')
  );
}

module.exports = {
  claudeOwnedPaths,
  writeClaudeIntegration,
  writeHookSettings,
  writeCodeReviewAgentHookSettings,
  claudeIntegrationComplete,
};
