const fs = require('node:fs');
const path = require('node:path');
const {
  COPILOT_INSTRUCTION_DEFINITIONS,
  COPILOT_MD_SNIPPET,
  MARKERS,
} = require('../constants');
const {
  assertCanWriteOwnedFiles,
  isTenetsOwnedFile,
  upsertMarkedContent,
  writeOwnedFile,
} = require('./file-writer');
const {
  writeReviewCommand,
  reviewCommandPath,
  reviewCommandExists,
} = require('./review-command-writer');
const {
  writeScaffoldCommand,
  scaffoldCommandPath,
  scaffoldCommandExists,
} = require('./scaffold-command-writer');

function buildCopilotInstructionFile(definition, content) {
  const section = content.sections.find(
    (candidate) => candidate.section === definition.contentSection
  );
  const parts = [
    '---',
    `applyTo: "${definition.applyTo}"`,
    '---',
    '',
    MARKERS.start,
    `# Tenets: ${definition.contentSection} Rules`,
    '',
    '> Auto-generated by Tenets. Run `npx tenets update` to update.',
    '',
  ];

  for (const file of section?.files || []) {
    parts.push(file.content.trim(), '');
  }

  parts.push(MARKERS.end, '');
  return parts.join('\n');
}

function copilotOwnedPaths(projectRoot) {
  return [
    ...COPILOT_INSTRUCTION_DEFINITIONS.map((definition) =>
      path.join(
        projectRoot,
        '.github',
        'instructions',
        definition.fileName
      )
    ),
    reviewCommandPath(projectRoot, 'copilot'),
    scaffoldCommandPath(projectRoot, 'copilot'),
  ];
}

function writeCopilotIntegration(projectRoot, content, options = {}) {
  assertCanWriteOwnedFiles(copilotOwnedPaths(projectRoot), options);
  const globalInstructionsPath = path.join(
    projectRoot,
    '.github',
    'copilot-instructions.md'
  );
  const globalAction = upsertMarkedContent(
    globalInstructionsPath,
    COPILOT_MD_SNIPPET,
    '# GitHub Copilot Instructions'
  );

  const instructionsDir = path.join(projectRoot, '.github', 'instructions');
  fs.mkdirSync(instructionsDir, { recursive: true });

  const writtenFiles = ['.github/copilot-instructions.md'];
  for (const definition of COPILOT_INSTRUCTION_DEFINITIONS) {
    const instructionPath = path.join(instructionsDir, definition.fileName);
    writeOwnedFile(
      instructionPath,
      buildCopilotInstructionFile(definition, content),
      options
    );
    writtenFiles.push(`.github/instructions/${definition.fileName}`);
  }

  writtenFiles.push(writeReviewCommand(projectRoot, 'copilot', {
    ...options,
    content,
  }));
  writtenFiles.push(writeScaffoldCommand(projectRoot, 'copilot', options));
  return { writtenFiles, globalAction };
}

function copilotInstructionsExist(projectRoot) {
  return copilotOwnedPaths(projectRoot).some((filePath) =>
    fs.existsSync(filePath)
  );
}

function copilotIntegrationComplete(projectRoot) {
  const globalInstructionsPath = path.join(
    projectRoot,
    '.github',
    'copilot-instructions.md'
  );
  const hasGlobalInstructions =
    fs.existsSync(globalInstructionsPath) &&
    fs.readFileSync(globalInstructionsPath, 'utf-8').includes(MARKERS.start);
  const hasScopedInstructions = COPILOT_INSTRUCTION_DEFINITIONS.every(
    (definition) =>
      isTenetsOwnedFile(
        path.join(
          projectRoot,
          '.github',
          'instructions',
          definition.fileName
        )
      )
  );

  return (
    hasGlobalInstructions &&
    hasScopedInstructions &&
    reviewCommandExists(projectRoot, 'copilot') &&
    scaffoldCommandExists(projectRoot, 'copilot')
  );
}

module.exports = {
  buildCopilotInstructionFile,
  copilotOwnedPaths,
  writeCopilotIntegration,
  copilotInstructionsExist,
  copilotIntegrationComplete,
};
