const fs = require('node:fs');
const path = require('node:path');
const {
  COPILOT_INSTRUCTION_DEFINITIONS,
  COPILOT_MD_SNIPPET,
  MARKERS,
} = require('../constants');
const { upsertMarkedContent } = require('./file-writer');
const {
  writeReviewCommand,
  reviewCommandExists,
} = require('./review-command-writer');

function buildCopilotInstructionFile(definition, content) {
  const section = content.sections.find(
    (candidate) => candidate.section === definition.contentSection
  );
  const parts = [
    '---',
    `applyTo: "${definition.applyTo}"`,
    '---',
    '',
    MARKERS.start,
    `# Tenets: ${definition.contentSection} Rules`,
    '',
    '> Auto-generated by Tenets. Run `npx tenets update` to update.',
    '',
  ];

  for (const file of section?.files || []) {
    parts.push(file.content.trim(), '');
  }

  parts.push(MARKERS.end, '');
  return parts.join('\n');
}

function writeCopilotIntegration(projectRoot, content) {
  const globalInstructionsPath = path.join(
    projectRoot,
    '.github',
    'copilot-instructions.md'
  );
  const globalAction = upsertMarkedContent(
    globalInstructionsPath,
    COPILOT_MD_SNIPPET,
    '# GitHub Copilot Instructions'
  );

  const instructionsDir = path.join(projectRoot, '.github', 'instructions');
  fs.mkdirSync(instructionsDir, { recursive: true });

  const writtenFiles = ['.github/copilot-instructions.md'];
  for (const definition of COPILOT_INSTRUCTION_DEFINITIONS) {
    const instructionPath = path.join(instructionsDir, definition.fileName);
    fs.writeFileSync(
      instructionPath,
      buildCopilotInstructionFile(definition, content),
      'utf-8'
    );
    writtenFiles.push(`.github/instructions/${definition.fileName}`);
  }

  writtenFiles.push(writeReviewCommand(projectRoot, 'copilot'));
  return { writtenFiles, globalAction };
}

function copilotInstructionsExist(projectRoot) {
  return COPILOT_INSTRUCTION_DEFINITIONS.some((definition) =>
    fs.existsSync(
      path.join(projectRoot, '.github', 'instructions', definition.fileName)
    )
  );
}

function copilotIntegrationComplete(projectRoot) {
  const globalInstructionsPath = path.join(
    projectRoot,
    '.github',
    'copilot-instructions.md'
  );
  const hasGlobalInstructions =
    fs.existsSync(globalInstructionsPath) &&
    fs.readFileSync(globalInstructionsPath, 'utf-8').includes(MARKERS.start);
  const hasScopedInstructions = COPILOT_INSTRUCTION_DEFINITIONS.every(
    (definition) =>
      fs.existsSync(
        path.join(
          projectRoot,
          '.github',
          'instructions',
          definition.fileName
        )
      )
  );

  return (
    hasGlobalInstructions &&
    hasScopedInstructions &&
    reviewCommandExists(projectRoot, 'copilot')
  );
}

module.exports = {
  buildCopilotInstructionFile,
  writeCopilotIntegration,
  copilotInstructionsExist,
  copilotIntegrationComplete,
};
