const fs = require('node:fs');
const path = require('node:path');
const { CURSOR_RULE_DEFINITIONS, MARKERS } = require('../constants');
const {
  assertCanWriteOwnedFiles,
  isTenetsOwnedFile,
  removeMarkedContent,
  writeOwnedFile,
} = require('./file-writer');
const {
  writeReviewCommand,
  reviewCommandPath,
  reviewCommandExists,
} = require('./review-command-writer');

function buildCursorRuleFile(definition, content) {
  const section = content.sections.find(
    (candidate) => candidate.section === definition.contentSection
  );
  const parts = [
    '---',
    `description: "${definition.description}"`,
    `globs: "${definition.globs}"`,
    `alwaysApply: ${definition.alwaysApply}`,
    '---',
    '',
    MARKERS.start,
  ];

  if (definition.includeIntroduction) {
    parts.push(content.introduction.trim(), '');
  }

  parts.push(`# Tenets: ${definition.contentSection} Rules`, '');
  parts.push('> Auto-generated by Tenets. Run `npx tenets update` to update.', '');

  for (const file of section?.files || []) {
    parts.push(file.content.trim(), '');
  }

  parts.push(MARKERS.end, '');
  return parts.join('\n');
}

function cursorOwnedPaths(projectRoot) {
  return [
    ...CURSOR_RULE_DEFINITIONS.map((definition) =>
      path.join(projectRoot, '.cursor', 'rules', definition.fileName)
    ),
    reviewCommandPath(projectRoot, 'cursor'),
  ];
}

function writeCursorIntegration(projectRoot, content, options = {}) {
  const rulesDir = path.join(projectRoot, '.cursor', 'rules');
  assertCanWriteOwnedFiles(cursorOwnedPaths(projectRoot), options);
  fs.mkdirSync(rulesDir, { recursive: true });

  const writtenFiles = [];
  for (const definition of CURSOR_RULE_DEFINITIONS) {
    const rulePath = path.join(rulesDir, definition.fileName);
    writeOwnedFile(
      rulePath,
      buildCursorRuleFile(definition, content),
      options
    );
    writtenFiles.push(`.cursor/rules/${definition.fileName}`);
  }

  writtenFiles.push(writeReviewCommand(projectRoot, 'cursor', options));

  const legacyPath = path.join(projectRoot, '.cursorrules');
  const removedLegacyRules = removeMarkedContent(legacyPath);

  return { writtenFiles, removedLegacyRules };
}

function cursorRulesExist(projectRoot) {
  return cursorOwnedPaths(projectRoot).some((filePath) =>
    fs.existsSync(filePath)
  );
}

function cursorIntegrationComplete(projectRoot) {
  return (
    CURSOR_RULE_DEFINITIONS.every((definition) =>
      isTenetsOwnedFile(
        path.join(projectRoot, '.cursor', 'rules', definition.fileName)
      )
    ) && reviewCommandExists(projectRoot, 'cursor')
  );
}

module.exports = {
  buildCursorRuleFile,
  cursorOwnedPaths,
  writeCursorIntegration,
  cursorRulesExist,
  cursorIntegrationComplete,
};
