const fs = require('node:fs');
const path = require('node:path');
const { GENERATED_MARKER, MARKERS } = require('../constants');

class FileOwnershipConflictError extends Error {
  constructor(filePaths) {
    const formattedPaths = filePaths.map((filePath) => `  ${filePath}`).join('\n');
    super(
      'Refusing to overwrite files that are not owned by Tenets:\n' +
      `${formattedPaths}\n` +
      'Review the files, then move or remove them before retrying.'
    );
    this.name = 'FileOwnershipConflictError';
    this.filePaths = filePaths;
  }
}

function ensureDir(filePath) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function writeFile(filePath, content, mode) {
  ensureDir(filePath);

  if (mode === 'append') {
    const existing = fs.existsSync(filePath)
      ? fs.readFileSync(filePath, 'utf-8')
      : '';
    const separator = existing.length > 0 && !existing.endsWith('\n') ? '\n\n' : '\n';
    fs.writeFileSync(filePath, existing + separator + content, 'utf-8');
  } else {
    fs.writeFileSync(filePath, content, 'utf-8');
  }
}

function hasValidMarkers(content) {
  const startIdx = content.indexOf(MARKERS.start);
  const endIdx = content.indexOf(MARKERS.end);
  return startIdx !== -1 && endIdx !== -1 && endIdx > startIdx;
}

function isTenetsOwnedContent(content) {
  return (
    hasValidMarkers(content) ||
    content.includes(GENERATED_MARKER) ||
    content.includes('tenets:generated') ||
    /auto-generated by tenets/i.test(content) ||
    /PostToolUse hook for tenets architecture monitoring/i.test(content) ||
    /name: code-review-agent[\s\S]*You are the Tenets code review agent/i.test(content)
  );
}

function isTenetsOwnedFile(filePath) {
  return (
    fs.existsSync(filePath) &&
    isTenetsOwnedContent(fs.readFileSync(filePath, 'utf-8'))
  );
}

function findOwnershipConflicts(filePaths) {
  return filePaths.filter(
    (filePath) => fs.existsSync(filePath) && !isTenetsOwnedFile(filePath)
  );
}

function assertCanWriteOwnedFiles(filePaths, options = {}) {
  if (options.overwriteConflicts) {
    return;
  }

  const conflicts = findOwnershipConflicts(filePaths);
  if (conflicts.length > 0) {
    throw new FileOwnershipConflictError(conflicts);
  }
}

function writeOwnedFile(filePath, content, options = {}) {
  if (!isTenetsOwnedContent(content)) {
    throw new Error(
      `Refusing to write generated file without a Tenets ownership marker: ${filePath}`
    );
  }
  assertCanWriteOwnedFiles([filePath], options);
  ensureDir(filePath);
  const action = fs.existsSync(filePath) ? 'updated' : 'created';
  fs.writeFileSync(filePath, content, 'utf-8');
  return action;
}

function replaceMarkedContent(filePath, newContent) {
  if (!fs.existsSync(filePath)) {
    return false;
  }

  const existing = fs.readFileSync(filePath, 'utf-8');
  const startIdx = existing.indexOf(MARKERS.start);
  const endIdx = existing.indexOf(MARKERS.end);

  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    return false;
  }

  const before = existing.substring(0, startIdx);
  const after = existing.substring(endIdx + MARKERS.end.length);

  fs.writeFileSync(filePath, before + newContent.trimEnd() + after, 'utf-8');
  return true;
}

function upsertMarkedContent(filePath, markedContent, initialHeading = '') {
  ensureDir(filePath);

  if (replaceMarkedContent(filePath, markedContent)) {
    return 'replaced';
  }

  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, 'utf-8');
    const separator = existing.length === 0
      ? ''
      : existing.endsWith('\n')
        ? '\n'
        : '\n\n';
    fs.writeFileSync(filePath, existing + separator + markedContent.trimEnd() + '\n', 'utf-8');
    return 'appended';
  }

  const prefix = initialHeading ? `${initialHeading.trimEnd()}\n\n` : '';
  fs.writeFileSync(filePath, prefix + markedContent.trimEnd() + '\n', 'utf-8');
  return 'created';
}

function removeMarkedContent(filePath) {
  if (!fs.existsSync(filePath)) {
    return false;
  }

  const existing = fs.readFileSync(filePath, 'utf-8');
  const startIdx = existing.indexOf(MARKERS.start);
  const endIdx = existing.indexOf(MARKERS.end);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    return false;
  }

  const before = existing.substring(0, startIdx).trimEnd();
  const after = existing.substring(endIdx + MARKERS.end.length).trimStart();
  const remaining = [before, after].filter(Boolean).join('\n\n');

  if (remaining.length === 0) {
    fs.unlinkSync(filePath);
  } else {
    fs.writeFileSync(filePath, remaining.trimEnd() + '\n', 'utf-8');
  }
  return true;
}

module.exports = {
  FileOwnershipConflictError,
  hasValidMarkers,
  writeFile,
  writeOwnedFile,
  isTenetsOwnedContent,
  isTenetsOwnedFile,
  findOwnershipConflicts,
  assertCanWriteOwnedFiles,
  replaceMarkedContent,
  upsertMarkedContent,
  removeMarkedContent,
};
